# Generated by Django 5.1 on 2025-03-23 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fashionitem',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
