# Generated by Django 5.1 on 2025-03-24 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_fashionitem_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fashionitem',
            name='image',
        ),
    ]
