# Generated by Django 5.1 on 2025-03-24 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_fashionitem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='fashionitem',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
