# Generated by Django 5.1 on 2025-03-24 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_fashionitem_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fashionitem',
            name='category',
        ),
    ]
