# Generated by Django 5.1 on 2025-03-25 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_fashionitem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='fashionitem',
            name='is_new',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fashionitem',
            name='is_sale',
            field=models.BooleanField(default=False),
        ),
    ]
