# Generated by Django 5.1 on 2025-03-25 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_fashionitem_is_new_fashionitem_is_sale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fashionitem',
            name='is_new',
        ),
        migrations.RemoveField(
            model_name='fashionitem',
            name='is_sale',
        ),
    ]
