# Generated by Django 5.1 on 2025-05-01 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_fashionitem_is_new_remove_fashionitem_is_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='fashionitem',
            name='is_new',
            field=models.BooleanField(default=False),
        ),
    ]
