# Generated by Django 5.1 on 2025-05-01 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_fashionitem_is_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fashionitem',
            name='is_new',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
