# Generated by Django 5.1 on 2025-05-01 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_fashionitem_is_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fashionitem',
            name='is_new',
        ),
    ]
